export const DEVELOPMENT_ENVIRONMENT = {
  NODE_ENV: process.env.NODE_ENV,
  PORT: process.env.PORT,
  MONGO_USERNAME: process.env.MONGO_USERNAME,
  MONGO_PASSWORD: process.env.MONGO_PASSWORD,
  MONGO_HOST_1: process.env.MONGO_HOST_1,
  MONGO_HOST_2: process.env.MONGO_HOST_2,
  MONGO_HOST_3: process.env.MONGO_HOST_3,
  MONGO_PORT: process.env.MONGO_PORT,
  MONGO_DB_NAME: process.env.MONGO_DB_NAME,
  BCRYPT_SALT_ROUNDS: process.env.BCRYPT_SALT_ROUNDS,
  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY
}
